version: "3.8"
services:
    build-agent:
        image: build-agent
        build:
            context: .
            dockerfile: ./build-agent/Dockerfile
    test-agent:
        image: test-agent
        build:
            context: .
            dockerfile: ./test-agent/Dockerfile
        depends_on:
            - build-agent
